MvcPaging/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcPaging.Controllers
{
    public class DetailsController : Controller
    {        
        public ActionResult ViewPost()
        {
            return View();
        }
    }
}

MvcPaging/Controllers/MustachePagingController.cs
using System.Web.Mvc;

namespace MvcPaging.Controllers
{
    public class MustachePagingController : BasePagingController
    {
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult LoadMorePosts(int currentPageNumber)
        {
            var model = GetModel(currentPageNumber);
            return Json(model, JsonRequestBehavior.AllowGet);
        }
    }
}

MvcPaging/Controllers/MvcPagingController.cs
using System.Web.Mvc;

namespace MvcPaging.Controllers
{
    public class MvcPagingController : BasePagingController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LoadMorePosts(int currentPageNumber)
        {
            var model = GetModel(currentPageNumber);
            return PartialView("PostDisplayer", model);
        }
    }
}

MvcPaging/Views/Shared/PostDisplayer.cshtml
@model MvcPaging.Models.PostViewModel

@foreach (var post in Model.Posts)
{
    <div class="post-entry" id="@string.Format("post-{0}", post.PostId)">
        <div>
            <div class="pull-left" title="@post.PostTitle">
                @post.PostTitle
            </div>
            <div class="pull-right" style="color: #BDBDBD">
                <b>@post.Category</b>
            </div>
        </div>
        <br/><br/><br/>
        @Html.ActionLink("View", "ViewPost", "Details", new { questionId = post.PostId }, new { @class = "btn btn-primary" })
    </div>
    <hr/>
}

MvcPaging/Views/Shared/PostsPartial.cshtml
@model MvcPaging.Models.PostViewModel

<div id="content">
    @Html.Partial("PostDisplayer", Model)
</div>

<div id="placeholder">
    
</div>

<div>
    <a class="btn btn-more" id="moreBtn">
        More&nbsp;<img id="moreBtnImg" src="@Url.Content("~/Content/images/loading.gif")" alt="loading..."/>
    </a>
</div>

<input type="hidden" id="currentPage" name="currentPage" value="1"/>

MvcPaging/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>MVC Paging</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }

      .btn-more {
          width: 100%
      }

      #moreBtnImg {
          display: none; 
          width: 12px; 
          height: 12px
      }
    </style>
    <link href="@Url.Content("~/Content/bootstrap-responsive.css")" rel="stylesheet">
  </head>

  <body>
      
    <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
    <div class="container">
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <a class="brand" href="@Url.Action("Index","Home")">Paging</a>
        <div class="nav-collapse collapse">
        <ul class="nav">
            <li class="active">@Html.ActionLink("Home","Index","Home")</li>
            <li>@Html.ActionLink("Pure MVC Paging", "Index", "MvcPaging")</li>
            <li>@Html.ActionLink("Mustache Paging", "Index", "MustachePaging")</li>            
        </ul>
        </div><!--/.nav-collapse -->
    </div>
    </div>
</div>

<div class="container">
    
    @RenderBody()

    <hr />
        

    <footer>
    <p>&copy; Company 2013</p>
    </footer>

</div> <!-- /container -->

      <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="@Url.Content("~/Scripts/jquery-2.0.3.js")"></script>
      <script src="@Url.Content("~/Scripts/bootstrap.js")"></script>    
      <script type="text/javascript">
          var siteRoot = '@Url.Content("~/")';
      </script>
      @RenderSection("pageScripts", false)
  </body>
</html>